package helper;

public class Payload {

	
	public static String actualJson() {
		
		return "{\r\n"
				+ "\"data\": {\r\n"
				+ "\"domainId\": 0,\r\n"
				+ "\"outOfOfficeAutoReply\": false,\r\n"
				+ "\"customerVerificationTemplate\": \"Please find the {{.verificationCode}}. Provide the same to the {{.senderFullName}} when requested. \",\r\n"
				+ "\"outOfOfficeTemplate\": \"\",\r\n"
				+ "\"timezone\": \"Asia/Kolkata\",\r\n"
				+ "\"workingDays\": {\r\n"
				+ "\"workingDay\": [\r\n"
				+ "true,\r\n"
				+ "true,\r\n"
				+ "true,\r\n"
				+ "true,\r\n"
				+ "true,\r\n"
				+ "true,\r\n"
				+ "true\r\n"
				+ "],\r\n"
				+ "\"workingHoursFrom\": [\r\n"
				+ "\"09:30\",\r\n"
				+ "\"00:00\",\r\n"
				+ "\"00:00\",\r\n"
				+ "\"09:30\",\r\n"
				+ "\"07:30\",\r\n"
				+ "\"09:30\",\r\n"
				+ "\"09:30\"\r\n"
				+ "],\r\n"
				+ "\"workingHoursTo\": [\r\n"
				+ "\"20:30\",\r\n"
				+ "\"23:45\",\r\n"
				+ "\"23:45\",\r\n"
				+ "\"18:30\",\r\n"
				+ "\"18:30\",\r\n"
				+ "\"18:30\",\r\n"
				+ "\"18:30\"\r\n"
				+ "]\r\n"
				+ "},\r\n"
				+ "\"enableDocuSign\": false,\r\n"
				+ "\"docuSignApiKey\": \"\",\r\n"
				+ "\"docuSignSecretKey\": \"\",\r\n"
				+ "\"docuSignEnv\": \"\",\r\n"
				+ "\"docuSignTemplate\": \"\",\r\n"
				+ "\"enableMessagePay\": true,\r\n"
				+ "\"messagePayApiEmail\": \"\",\r\n"
				+ "\"messagePayApiPassword\": \"\",\r\n"
				+ "\"messagePayTemplate\": \" {{.messagePayUrl}} {{.userFullName}}, {{.userFirstName}}, {{.userLastName}}\",\r\n"
				+ "\"messagePayEnv\": \"sandbox\",\r\n"
				+ "\"enableEllieMae\": true,\r\n"
				+ "\"ellieMaeApiKey\": \"\",\r\n"
				+ "\"ellieMaeClientId\": \"\",\r\n"
				+ "\"ellieMaeInstanceId\": \"\",\r\n"
				+ "\"ellieMaeEltropyToken\": \"4a54-9a89-45ce90dcdde4\",\r\n"
				+ "\"enableInComingMessageModeration\": false,\r\n"
				+ "\"disableLeadEditing\": false,\r\n"
				+ "\"createdBy\": 0,\r\n"
				+ "\"lastUpdatedBy\": 0,\r\n"
				+ "\"version\": 0,\r\n"
				+ "\"managers\": null\r\n"
				+ "},\r\n"
				+ "\"message\": \"Saved/updated domain settings successfully.\",\r\n"
				+ "\"status\": \"Ok\"\r\n"
				+ "}";
		
	}
	
	
	public static String expectedJson() {
		
		return "{\r\n"
				+ "\"data\": {\r\n"
				+ "\"domainId\": 0,\r\n"
				+ "\"outOfOfficeAutoReply\": false,\r\n"
				+ "\"customerVerificationTemplate\": \"Please find the {{.verificationCode}}. Provide the same to the {{.senderFullName}} when requested. \",\r\n"
				+ "\"outOfOfficeTemplate\": \"\",\r\n"
				+ "\"timezone\": \"Asia/Chennai\",\r\n"
				+ "\"workingDays\": {\r\n"
				+ "\"workingDay\": [\r\n"
				+ "true,\r\n"
				+ "true,\r\n"
				+ "true,\r\n"
				+ "true,\r\n"
				+ "true,\r\n"
				+ "true,\r\n"
				+ "true\r\n"
				+ "],\r\n"
				+ "\"workingHoursFrom\": [\r\n"
				+ "\"09:30\",\r\n"
				+ "\"09:30\"\r\n"
				+ "],\r\n"
				+ "\"workingHoursTo\": [\r\n"
				+ "\"20:30\",\r\n"
				+ "\"23:45\",\r\n"
				+ "\"23:45\",\r\n"
				+ "\"18:30\",\r\n"
				+ "\"18:30\",\r\n"
				+ "\"18:30\",\r\n"
				+ "\"18:30\"\r\n"
				+ "]\r\n"
				+ "},\r\n"
				+ "\"enableDocuSign\": false,\r\n"
				+ "\"docuSignApiKey\": \"\",\r\n"
				+ "\"docuSignSecretKey\": \"\",\r\n"
				+ "\"docuSignEnv\": \"\",\r\n"
				+ "\"docuSignTemplate\": \"\",\r\n"
				+ "\"enableMessagePay\": true,\r\n"
				+ "\"messagePayApiEmail\": \"\",\r\n"
				+ "\"messagePayApiPassword\": \"\",\r\n"
				+ "\"messagePayTemplate\": \" {{.messagePayUrl}} {{.userFullName}}, {{.userFirstName}}, {{.userLastName}}\",\r\n"
				+ "\"messagePayEnv\": \"sandbox\",\r\n"
				+ "\"enableEllieMae\": true,\r\n"
				+ "\"ellieMaeApiKey\": \"\",\r\n"
				+ "\"ellieMaeClientId\": \"\",\r\n"
				+ "\"ellieMaeInstanceId\": \"\",\r\n"
				+ "\"ellieMaeEltropyToken\": \"4a54-fdf3rf-dde4\",\r\n"
				+ "\"enableInComingMessageModeration\": false,\r\n"
				+ "\"disableLeadEditing\": false,\r\n"
					+ "\"workingHoursTo\": [\r\n"
				+ "\"20:30\",\r\n"
				+ "\"23:45\",\r\n"
				+ "\"23:45\",\r\n"
				+ "\"18:30\",\r\n"
				+ "\"18:30\",\r\n"
				+ "\"18:30\",\r\n"
				+ "\"18:30\"\r\n"
				+ "]\r\n"
				+ "},\r\n"
				+ "\"enableDocuSign\": false,\r\n"
				+ "\"docuSignApiKey\": \"\",\r\n"
				+ "\"docuSignSecretKey\": \"\",\r\n"
				+ "\"docuSignEnv\": \"\",\r\n"
				+ "\"docuSignTemplate\": \"\",\r\n"
				+ "\"enableMessagePay\": true,\r\n"
				+ "\"messagePayApiEmail\": \"\",\r\n"
				+ "\"messagePayApiPassword\": \"\",\r\n"
				+ "\"messagePayTemplate\": \" {{.messagePayUrl}} {{.userFullName}}, {{.userFirstName}}, {{.userLastName}}\",\r\n"
				+ "\"messagePayEnv\": \"sandbox\",\r\n"
				+ "\"enableEllieMae\": true,\r\n"
				+ "\"ellieMaeApiKey\": \"\",\r\n"
				+ "\"ellieMaeClientId\": \"\",\r\n"
				+ "\"ellieMaeInstanceId\": \"\",\r\n"
				+ "\"ellieMaeEltropyToken\": \"4a54-9a89-45ce90dcdde4\",\r\n"
				+ "\"enableInComingMessageModeration\": false,\r\n"
				+ "\"disableLeadEditing\": false,\r\n"
				+ "\"createdBy\": 0,\r\n"
				+ "\"lastUpdatedBy\": 0,\r\n"
				+ "\"version\": 0,\r\n"
				+ "\"managers\": null\r\n"
				+ "},\r\n"
				+ "\"message\": \"Saved/updated domain settings successfully.\",\r\n"
				+ "\"status\": \"Ok\"\r\n"
				+ "}";
		
	
	}
	
	
	
	
	
	
	
	
}
